apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-matrix-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-matrix
  params:
    - name: runner_image
      value: quay.io/klape/llm-d-e2e@sha256:62649eb945461fb6c6fc3a919487a9432d0117a4ec31bf59c10728c7ce223ad1
    - name: namespace
      value: klape-llm-d-e2e
    - name: retain_on_failure
      value: "true"
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-runner
  workspaces:
    - name: results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
