apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-matrix-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-matrix
  params:
    - name: runner_image
      value: quay.io/klape/llm-d-e2e@sha256:aa3a87af47b9aacc5e2d4a492bad1e7433181ac1dc8f67576a2216d1eca351c3
    - name: namespace
      value: klape-llm-d-e2e
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-runner
  workspaces:
    - name: results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
