apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-image-build-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-image-build
  params:
    - name: git-url
      value: https://github.com/kylape/llm-d-e2e.git
    - name: revision
      value: codex/INFERENG-10381-burrito-matrix
    - name: output-image
      value: quay.io/klape/llm-d-e2e:tekton-poc
    - name: dockerfile
      value: Dockerfile.tekton
    - name: context
      value: .
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-image-builder
  workspaces:
    - name: registry-auth
      secret:
        secretName: klape-tekton-pull-secret
