apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-matrix-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-matrix
  params:
    - name: runner_image
      value: quay.io/klape/llm-d-e2e@sha256:00495a14fc89de3d4a80e171d429639c7ec2af580ce53c5e15ed21a3423c1f44
    - name: namespace
      value: klape-llm-d-e2e
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-runner
  workspaces:
    - name: results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
