apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-matrix-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-matrix
  params:
    - name: runner_image
      value: quay.io/klape/llm-d-e2e@sha256:8a98ddb9c2997ac70ec593f698bf1eb380b7a81236b8c946a2c186690316dddd
    - name: namespace
      value: klape-llm-d-e2e
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-runner
  workspaces:
    - name: results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
