apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-e2e-matrix-
  namespace: klape-llm-d-e2e
spec:
  pipelineRef:
    name: llm-d-e2e-matrix
  params:
    - name: runner_image
      value: quay.io/klape/llm-d-e2e@sha256:d2faecc527637ea8562c1cc9c12b8ab428e434c0c1ca16ef81ce07e782b02cb3
    - name: namespace
      value: klape-llm-d-e2e
  taskRunTemplate:
    serviceAccountName: llm-d-e2e-runner
  workspaces:
    - name: results
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
