apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: klape-llm-d-e2e

resources:
  - tasks/deploy.yaml
  - tasks/smoke-test.yaml
  - tasks/cleanup.yaml
  - tasks/matrix-qualification.yaml
  - pipeline.yaml
  - pipeline-matrix.yaml
