apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: llm-d-maas-validate-
spec:
  pipelineRef:
    name: llm-d-maas-validate
  workspaces:
    - name: guest-kubeconfig
      secret:
        secretName: llm-d-e2e-guest-kubeconfig
